# Generated by Django 5.2.8 on 2025-11-26 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paginas', '0004_compra'),
    ]

    operations = [
        migrations.AddField(
            model_name='compra',
            name='licencia',
            field=models.CharField(default='TEMP', max_length=32, unique=True),
            preserve_default=False,
        ),
    ]
