# Generated by Django 5.2.8 on 2025-11-27 13:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('paginas', '0005_compra_licencia'),
    ]

    operations = [
        migrations.CreateModel(
            name='DestacadoInicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=150, verbose_name='Título')),
                ('descripcion_corta', models.CharField(max_length=255, verbose_name='Descripción corta')),
                ('es_oferta', models.BooleanField(default=False, help_text='Marcar si esta tarjeta corresponde a una oferta especial.', verbose_name='¿Es una oferta?')),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='destacados/', verbose_name='Imagen (opcional)')),
                ('activo', models.BooleanField(default=True, verbose_name='¿Mostrar en inicio?')),
                ('orden', models.PositiveIntegerField(default=0, help_text='Orden de aparición en inicio (0 primero).', verbose_name='Orden')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('producto', models.ForeignKey(blank=True, help_text='Producto al que se redirige el botón de la tarjeta (opcional).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='destacados_inicio', to='paginas.pagina', verbose_name='Producto asociado')),
            ],
            options={
                'verbose_name': 'Destacado de inicio',
                'verbose_name_plural': 'Destacados de inicio',
                'ordering': ['orden', '-fecha_creacion'],
            },
        ),
    ]
