# Generated by Django 5.2.8 on 2025-11-26 15:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cuentas', '0003_tarjetaregalo'),
    ]

    operations = [
    ]
